export const FETCH_SEARCH_REQUEST = 'FETCH_SEARCH_REQUEST';

export const TOGGLE_BANNER_PANEL = 'TOGGLE_BANNER_PANEL';

export const TOGGLE_CONTENT_PANEL = 'TOGGLE_CONTENT_PANEL';

export const CLEAR_DATA_SERVER = 'CLEAR_DATA_SERVER';

export const USER_SEARCH_VALUE = 'USER_SEARCH_VALUE';

export const FETCH_SEARCH_RECEIVED = 'FETCH_SEARCH_RECEIVED';

export const FETCH_NEIGHBORHOOD_ITEMS = 'FETCH_NEIGHBORHOOD_ITEMS';

export const FETCH_LOCATION_ITEMS = 'FETCH_LOCATION_ITEMS';

export const FETCH_ERROR_MESSAGE = 'FETCH_ERROR_MESSAGE';