export const FETCH_SEARCH_REQUEST = 'FETCH_SEARCH_REQUEST';

export const TOGGLE_BANNER_PANEL = 'TOGGLE_BANNER_PANEL';

export const TOGGLE_CONTENT_PANEL = 'TOGGLE_CONTENT_PANEL';

export const CLEAR_DATA_SERVER = 'CLEAR_DATA_SERVER';

export const USER_SEARCH_VALUE = 'USER_SEARCH_VALUE';